import { useState } from 'react';
import { useRecords, saveRecord, archiveRecord } from '../records';
import { adminRequest, publicAppUrl } from '../api';
import Dialog from '../components/Dialog';
const newQuestion = () => ({ id: crypto.randomUUID(), label: '', type: 'text', required: false, options: [] });
export default function SurveysPage() {
  const surveys = useRecords('surveys');
  const [editing, setEditing] = useState(null), [busy, setBusy] = useState(false), [notice, setNotice] = useState(''), [archived, setArchived] = useState(false), [prompt, setPrompt] = useState('');
  async function run(fn) { setBusy(true); setNotice(''); try { await fn(); } catch (e) { setNotice(e.message); } finally { setBusy(false); } }
  function question(index, field, value) { setEditing(s => ({ ...s, questions: s.questions.map((q, i) => i === index ? { ...q, [field]: value } : q) })); }
  return <div className="client-workspace space-y-6"><header><h1 className="text-2xl font-bold">Surveys</h1><p>Create and edit surveys without relying on AI. Existing responses are preserved.</p><button onClick={() => setEditing({ title: '', description: '', active: false, questions: [newQuestion()] })}>New survey</button></header>
    {(notice || surveys.error) && <p role="alert">{notice || surveys.error} {surveys.error && <button onClick={surveys.retry}>Retry</button>}</p>}
    <label><input type="checkbox" checked={archived} onChange={e => setArchived(e.target.checked)} /> Show archived surveys</label>
    {surveys.loading ? <p role="status">Loading surveys…</p> : surveys.records.filter(s => Boolean(s.archivedAt) === archived).map(s => <article className="workspace-section" key={s.id}><h2>{s.title}</h2><p>{s.description}</p><p>{s.active ? 'Published' : 'Closed'} · {s.questions?.length || 0} questions</p><div className="flex flex-wrap gap-3"><button onClick={() => setEditing({ ...s, questions: (s.questions || []).map(q => ({ ...q })) })}>Edit survey</button><button disabled={busy} onClick={() => run(() => archiveRecord('surveys', s))}>{s.archivedAt ? 'Restore as closed' : 'Archive'}</button>{s.active && !s.archivedAt && <button onClick={() => run(async () => { await navigator.clipboard.writeText(publicAppUrl(`s/${s.publicId || s.id}`)); setNotice('Survey link copied.'); })}>Copy public link</button>}</div></article>)}
    {surveys.hasMore && <button onClick={surveys.loadMore}>Load more surveys</button>}
    {editing && <Dialog title={editing.id ? 'Edit survey' : 'New survey'} onClose={() => !busy && setEditing(null)}>{notice && <p role="alert">{notice}</p>}<form className="workspace-form" onSubmit={e => { e.preventDefault(); run(async () => { await saveRecord('surveys', editing, editing.id ? editing : null); setEditing(null); setNotice('Survey saved.'); }); }}>
      <label>Title<input required value={editing.title} onChange={e => setEditing({ ...editing, title: e.target.value })} /></label><label>Description<textarea value={editing.description || ''} onChange={e => setEditing({ ...editing, description: e.target.value })} /></label><label><input type="checkbox" checked={editing.active} onChange={e => setEditing({ ...editing, active: e.target.checked })} /> Published (publicly accessible)</label>
      {editing.questions.map((q, i) => <fieldset key={q.id}><legend>Question {i + 1}</legend><label>Question text<input required value={q.label} onChange={e => question(i, 'label', e.target.value)} /></label><label>Answer type<select value={q.type} onChange={e => question(i, 'type', e.target.value)}>{['text', 'textarea', 'email', 'number', 'select', 'radio', 'checkbox', 'tel', 'date'].map(t => <option key={t}>{t}</option>)}</select></label>{['select', 'radio', 'checkbox'].includes(q.type) && <label>Options (one per line)<textarea required value={(q.options || []).join('\n')} onChange={e => question(i, 'options', e.target.value.split('\n'))} /></label>}<label><input type="checkbox" checked={q.required} onChange={e => question(i, 'required', e.target.checked)} /> Required</label><button type="button" onClick={() => setEditing({ ...editing, questions: editing.questions.filter((_, index) => index !== i) })}>Remove question</button></fieldset>)}
      <button type="button" onClick={() => setEditing({ ...editing, questions: [...editing.questions, newQuestion()] })}>Add question</button><button disabled={busy}>Save survey</button>
    </form><details><summary>Optional AI question draft</summary><label>Describe the survey<textarea value={prompt} onChange={e => setPrompt(e.target.value)} /></label><button disabled={busy || !prompt.trim()} onClick={() => run(async () => { const result = await adminRequest('/api/ai-survey', { description: prompt }); setEditing({ ...editing, ...result.survey, id: editing.id, active: false }); })}>Generate draft using configured AI service</button><p>Generation uses the configured AI service only when requested. Review all questions before saving.</p></details></Dialog>}
  </div>;
}
